lights:
- {name: 'Vorne', 'waiting_time': 10, 'pose':[0,0,0], 'housecode': "12344321", addr_fs20: "3321"}
- {name: 'Hinten', 'waiting_time': 10, 'pose':[0,0,0], 'housecode': "12344321", addr_fs20: "3321"}
